export const LS_THEME = 'theme'
export const LS_SIDEBAR_TYPE = 'sidebar-type'
export const LS_SIDEBAR_STYLE = 'sidebar-style'
export const LS_LANG = 'lang'
export const LS_DRAWER_POS = 'drawer-pos'
export const LS_NAVBAR_TYPE = 'navbar-type'
export const LS_NAVBAR_STYLE = 'navbar-style'
